config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  # get 'static_pages/home'
  # get 'static_pages/help'
  # get 'static_pages/about'
  # get 'static_pages/contact'

  root to:'static_pages#home'
  get '/help', to:'static_pages#help'
  get '/about', to:'static_pages#about'
  get '/contact', to:'static_pages#contact'
  get '/sign_up', to:'users#new'





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/example_user.rb
class User
  attr_accessor :name, :email;

  def initialize(name, email)
    @name = name
    @email = email
  end
  def email_formatted
    "#{@name} and #{@email}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # attr_accessor :name, :email
  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true
      def new

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact

  end
  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #Return a full_title base on per-page

  def full_title(page_title)
    base_title = "Ruby on rails Tutorials Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'sample app', root_path, id: "logo", class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'Home',root_path%></li>
          <li><%= link_to "Help",help_path %></li>
        </ul>
<!--        <form class="navbar-form navbar-left">-->
<!--          <div class="form-group">-->
<!--            <input type="text" class="form-control" placeholder="Search">-->
<!--          </div>-->
<!--          <button type="submit" class="btn btn-default">Submit</button>-->
<!--        </form>-->
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign up", sign_up_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide :title, "About Us" %>
<h1>About Us Page</h1>

app/views/static_pages/contact.html.erb
  <% provide :title, "Contact Us" %>
  <h1>Contact Us Page</h1>

app/views/static_pages/help.html.erb
<% provide :title, 'Help' %>
<h1>How we can help you?</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide :title, 'Home' %>
<div class="jumbotron">
<h1 class="text-center">Sample App</h1>
<h2 class="text-center">This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
  <%= link_to 'Sign up now!', '#', class: "btn btn-lg btn-primary", style: "margin-top:25px" %>
</h2>
</div>
<%=link_to image_tag("rails.png", alt: "Rails", style: "width:100px; height:100px"), 'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>